mod analysis;
mod csv_file;
mod debug_file;
mod lib;
mod loc_file;
mod metainfo;
pub type Loc = loc_file::Loc;
pub type Tuple = analysis::Tuple;
pub type Relation = analysis::Relation;
pub type MetaInfo = metainfo::MetaInfo;
pub type SourceFile = lib::SourceFile;
