name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**.rs'
      - 'Cargo.*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust (Stable)
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Build
      run: cargo build --verbose --release

    - name: Upload build result
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: metavis
        path: target/release/metavis
