name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**.rs'
      - 'Cargo.*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ x86_64-unknown-linux-gnu, aarch64-apple-darwin ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust (Stable)
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Add cross
      run: wget -qO - https://github.com/cross-rs/cross/releases/latest/download/cross-x86_64-unknown-linux-gnu.tar.gz | tar -xzf - -C ~/.cargo/bin

    - name: Build
      run: cross build --verbose --release --target ${{ matrix.os }}

    - name: Upload build result
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: metavis
        path: |
          target/x86_64-unknown-linux-gnu/release/metavis
          target/aarch64-apple-darwin/release/metavis
